[build]
builder = "NIXPACKS"

[deploy]
startCommand = "PORT=$PORT node .next/standalone/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { NODE_ENV = "production" }